package student;

public enum StationLocation {
    NORTHERNMOST,
    SOUTHERNMOST,
    EASTERNMOST,
    WESTERNMOST,
    NORTHEASTERNMOST,
    NORTHWESTERNMOST,
    SOUTHEASTERNMOST,
    SOUTHWESTERNMOST,
    CENTERED;
}
